### ISSUE TITLE
Pod installation issue 

### ISSUE THREAD

**Issue by Lovyom** [fpotter/ExpandingDatePicker#1]
Analyzing dependencies
[!] Unable to find a specification for `ExpandingDatePicker`

Getting above error please check .... Is there any dependency for the above pod file installation

**Comment by fpotter** [comment]
HI @Lovyom — Can you try running `pod repo update`, then `pod update --verbose` or `pod install --verbose` again?

It has zero dependencies, so that shouldn't be an issue.  This doesn't repro for me.  The fact that it can't find the pod spec makes me think your locally cached copy of pod specs is out of date.

If it still fails for you after the above, try running the following to see how current your CocoaPods repo is.  You should see a commit with today's date —

```
git -C ~/.cocoapods/repos/master log -1
```

Let me know if that doesn't work...

**Comment by pimoon** [comment]
there is still the issue btw
